spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracking_db
    username: expense_tracking_user
    password: secret
  flyway:
    user: expense_tracking_user
    password: secret
server:
  port: 8080