spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
server:
  port: ${HTTP_PORT}